"""Static mapping tables for clinical study terminology normalization."""

from __future__ import annotations

# Phase mapping — covers all common abbreviations and variants
PHASE_MAP: dict[str, str] = {
    "phase i": "phase_1",
    "phase 1": "phase_1",
    "ph i": "phase_1",
    "ph 1": "phase_1",
    "phase ia": "phase_1",
    "phase ib": "phase_1",
    "phase 1a": "phase_1",
    "phase 1b": "phase_1",
    "ph ia": "phase_1",
    "ph ib": "phase_1",
    "phase i/ii": "phase_1_2",
    "phase 1/2": "phase_1_2",
    "phase i/2": "phase_1_2",
    "ph i/ii": "phase_1_2",
    "phase ii": "phase_2",
    "phase 2": "phase_2",
    "ph ii": "phase_2",
    "ph 2": "phase_2",
    "phase iia": "phase_2",
    "phase iib": "phase_2",
    "phase 2a": "phase_2",
    "phase 2b": "phase_2",
    "ph iia": "phase_2",
    "ph iib": "phase_2",
    "phase ii/iii": "phase_2_3",
    "phase 2/3": "phase_2_3",
    "ph ii/iii": "phase_2_3",
    "phase iii": "phase_3",
    "phase 3": "phase_3",
    "ph iii": "phase_3",
    "ph 3": "phase_3",
    "phase iiia": "phase_3",
    "phase iiib": "phase_3",
    "phase 3a": "phase_3",
    "phase 3b": "phase_3",
    "phase iii/iv": "phase_3_4",
    "phase 3/4": "phase_3_4",
    "phase iv": "phase_4",
    "phase 4": "phase_4",
    "ph iv": "phase_4",
    "ph 4": "phase_4",
}

BLINDING_MAP: dict[str, str] = {
    "open-label": "open_label",
    "open label": "open_label",
    "unblinded": "open_label",
    "single-blind": "single_blind",
    "single blind": "single_blind",
    "single-masked": "single_blind",
    "double-blind": "double_blind",
    "double blind": "double_blind",
    "double-masked": "double_blind",
    "triple-blind": "triple_blind",
    "triple blind": "triple_blind",
    "partially blinded": "partially_blinded",
    "partial blind": "partially_blinded",
    "observer-blind": "single_blind",
    "observer blind": "single_blind",
}

DRUG_FORM_MAP: dict[str, str] = {
    "oral tablet": "oral_tablet",
    "tablet": "oral_tablet",
    "tablets": "oral_tablet",
    "oral capsule": "oral_capsule",
    "capsule": "oral_capsule",
    "capsules": "oral_capsule",
    "oral solution": "oral_solution",
    "solution": "oral_solution",
    "subcutaneous": "injection_sc",
    "sc injection": "injection_sc",
    "sc": "injection_sc",
    "intramuscular": "injection_im",
    "im injection": "injection_im",
    "im": "injection_im",
    "intravenous": "infusion_iv",
    "iv infusion": "infusion_iv",
    "iv": "infusion_iv",
    "infusion": "infusion_iv",
    "topical": "topical",
    "inhaled": "inhaled",
    "inhalation": "inhaled",
    "intrathecal": "intrathecal",
    "ophthalmic": "ophthalmic",
}

# Frequency abbreviation expansions (for dosing.frequency normalization context)
FREQUENCY_ABBREV: dict[str, str] = {
    "qd": "once daily",
    "od": "once daily",
    "bid": "twice daily",
    "tid": "three times daily",
    "qid": "four times daily",
    "qw": "once weekly",
    "q2w": "every 2 weeks",
    "q3w": "every 3 weeks",
    "q4w": "every 4 weeks",
    "q6w": "every 6 weeks",
    "q8w": "every 8 weeks",
    "q12w": "every 12 weeks",
}

# Yes/no/not_specified enum
YES_NO_MAP: dict[str, str] = {
    "yes": "yes",
    "true": "yes",
    "y": "yes",
    "no": "no",
    "false": "no",
    "n": "no",
    "not specified": "not_specified",
    "not_specified": "not_specified",
    "unknown": "not_specified",
    "n/a": "not_specified",
    "na": "not_specified",
}
